#define DNA_BODY_SIZE_DEFAULT 1
#define DNA_BODY_UNIT 100
#define DNA_BODY_UNIT_DEFAULT 100
#define DNA_BODY_UNIT_MAX 150
#define DNA_BODY_UNIT_MIN 80

#define DNA_FEATURE_LIST list(\
	"mcolor" = COLOR_WHITE,\
	"body_size" = DNA_BODY_SIZE_DEFAULT,\
)
